=== libvo/bankapp/src/main/resources/xsd/PaymentRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">

  <xs:element name="PaymentRequest">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SenderCard" type="xs:string"/>
        <xs:element name="ReceiverCard" type="xs:string"/>
        <xs:element name="SenderAccount" type="xs:string"/>
        <xs:element name="ReceiverAccount" type="xs:string"/>
        <xs:element name="Amount" type="xs:decimal"/>
        <xs:element name="AcquirerBic" type="xs:string"/>
        <xs:element name="IssuerBic" type="xs:string"/>
        <xs:element name="ReceiverBic" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== libvo/bankapp/src/main/resources/xsd/payment.xml
<?xml version="1.0" encoding="UTF-8"?>
<PaymentRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="PaymentRequest.xsd">
  <SenderCard>1111222233334444</SenderCard>
  <ReceiverCard>5555666677778888</ReceiverCard>
  <SenderAccount>ACC-SENDER</SenderAccount>
  <ReceiverAccount>ACC-RECEIVER</ReceiverAccount>
  <Amount>1000.00</Amount>

  <AcquirerBic>BANK123</AcquirerBic>
  <IssuerBic>BANK123</IssuerBic>
  <ReceiverBic>BANK999</ReceiverBic>
</PaymentRequest>
